apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: noo-dev-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/netobserv/bpfman-operator-catalog:latest
  displayName: Network observability development catalog
  publisher: Me
  updateStrategy:
    registryPoll:
      interval: 1m
