apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: bpfman-fbc-4-19-20260604-151316
  namespace: ocp-bpfman-tenant
  labels:
    release.appstudio.openshift.io/author: 'alebedev87'
spec:
  releasePlan: catalog-4-19
  snapshot: catalog-4-19-20260604-151316-000
