schema: olm.template.basic
entries:
  - schema: olm.package
    name: bpfman-operator
    defaultChannel: preview
  - schema: olm.channel
    package: bpfman-operator
    name: preview
    entries:
      - name: bpfman-operator.vnext
  # TODO: Uncomment and update when Konflux builds are available.
  # - schema: olm.bundle
  #   # This should point to your latest CI-built bundle from Konflux.
  #   # Update this SHA whenever you want to test a new build.
  #   image: quay.io/redhat-user-workloads/ocp-bpfman-tenant/bpfman-operator-bundle-ystream:latest
  #   name: bpfman-operator.vnext